blousebrothers/cards/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from . import views


urlpatterns = [
    url(regex=r'^$',
        view=RedirectView.as_view(url=reverse_lazy('cards:home'), permanent=True),
        name='root'
        ),
    url(regex=r'^partenariatnico$',
        view=views.BouletListView.as_view(),
        name='boulet'
        ),
    url(
        r'^mes/fiches$',
        view=views.ListCardView.as_view(),
        name='list'
    ),
    url(
        r'^fiches/oubliees$',
        view=views.ListTrashedCardView.as_view(),
        name='trashed'
    ),
    url(
        r'^fiches/nonvues$',
        view=views.UnseenCardsListView.as_view(),
        name='unseen_cards_list'
    ),
    url(
        regex=r'^fiches/(?P<pk>\d+)/fin/$',
        view=views.FinalizeCardView.as_view(),
        name='finalize'
    ),
    url(
        regex=r'^fiche/create/$',
        view=views.CreateCardView.as_view(),
        name='create'
    ),
    url(
        regex=r'^fiche/(?P<pk>\d+)/edit$',
        view=views.UpdateCardView.as_view(),
        name='update'
    ),
    url(
        regex=r'^fiche/(?P<id>\w+)/stop$',
        view=views.RevisionCloseSessionView.as_view(),
        name='stop'
    ),
    url(
        regex=r'^oublie/(?P<pk>\d+)$',
        view=views.RevisionDeleteView.as_view(),
        name='delete'
    ),
    url(
        regex=r'^fiches$',
        view=views.RevisionRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^letsgo$',
        view=views.RevisionRedirectView.as_view(),
        name='start_new_session'
    ),
    url(
        regex=r'^fiche/suivante/([0-9]+)$',
        view=views.RevisionNextCardView.as_view(),
        name='next'
    ),
    url(
        regex=r'^fiche/precedente/([0-9]+)$',
        view=views.RevisionPreviousCardView.as_view(),
        name='previous'
    ),
    url(
        regex=r'^fiche/(?P<id>\d+)/(?P<dsp_card_on_load>\w*)?$',
        view=views.RevisionView.as_view(),
        name='revision'
    ),
    url(
        regex=r'^fiche/bookmark/([0-9]+)$',
        view=views.bookmark_card,
        name='bookmark'
    ),
    url(
        regex=r'^anki$',
        view=views.AnkiUploadView.as_view(),
        name='ankiupload'
    ),
    url(
        regex=r'^dashboard$',
        view=views.RevisionHome.as_view(),
        name='home'
    ),
    url(
        regex=r'^matieres$',
        view=views.RevisionGroups.as_view(),
        name='revision_groups'
    ),
]

blousebrothers/confs/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.views.generic.base import RedirectView

from . import views
from . import crud

from jchart.views import ChartView
from blousebrothers.users.charts import MeanBarChart
mb_chart = MeanBarChart()

urlpatterns = [
    url(regex=r'^$',
        view=RedirectView.as_view(url=reverse_lazy('catalogue:index'), permanent=True),
        name='root'
        ),
    url(
        r'^charts/mean_chart/(?P<user_id>\d+)/(?P<friend_id>\d+)?$',
        ChartView.from_chart(mb_chart),
        name='mb_chart'
    ),
    # URL pattern for the ConferenceHomeView
    url(
        r'^dashboard$',
        view=views.ConferenceHomeView.as_view(),
        name='home'
    ),
    # URL pattern for the ConferenceListView
    url(
        r'^mes_dossiers/?$',
        view=views.ConferenceListView.as_view(),
        name='list'
    ),

    # URL pattern for the TestUpdateView
    url(
        regex=r'^dossier/(?P<slug>[\w.@+-]+)$',
        view=views.TestUpdateView.as_view(),
        name='test'
    ),
    # URL pattern for the TestResetView
    url(
        regex=r'^dossier/(?P<slug>[\w.@+-]+)/resettest$',
        view=views.TestResetView.as_view(),
        name='test_reset'
    ),

    # URL pattern for the TestUpdateView
    url(
        regex=r'^dossier/(?P<slug>[\w.@+-]+)/resultats$',
        view=views.TestResult.as_view(),
        name='result'
    ),


    # URL pattern for the ConferenceDetailView
    url(
        regex=r'^dossier/(?P<slug>[\w.@+-]+)/$',
        view=views.ConferenceDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the ConferenceUpdateView
    url(
        regex=r'^creation/(?P<slug>[\w.@+-]+)/update$',
        view=views.ConferenceUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^~create/(?P<slug>[\w.@+-]+)/update$',
        view=RedirectView.as_view(pattern_name='confs:update', permanent=True),
        name='oldupdate'
    ),
    url(
        regex=r'^creation/(?P<slug>[\w.@+-]+)/delete$',
        view=views.ConferenceDeleteView.as_view(),
        name='delete'
    ),
    url(
        regex=r'^creation/(?P<slug>[\w.@+-]+)/final$',
        view=views.ConferenceFinalView.as_view(),
        name='final'
    ),
    # URL pattern for the ConferenceUpdateView
    url(
        regex=r'^creation/$',
        view=views.ConferenceCreateView.as_view(),
        name='create'
    ),
    url(
        regex=r'^creation/(?P<slug>[\w.@+-]+)/edit$',
        view=views.ConferenceEditView.as_view(),
        name='edit'
    ),
    url(r'^dossiers_faits/?$',
        views.BuyedConferenceListView.as_view(),
        name='my_confs'),

    url(r'^switch_correction$',
        view=views.ajax_switch_correction,
        name="switch_correction",
        ),
    url(r'^switch_for_sale$',
        view=views.ajax_switch_for_sale,
        name="switch_for_sale",
        ),


    #   #####  ############  #####   #
    #    ###   # CRUD API #   ###    #
    #     #    ############    #     #

    url(r'^crud/conference/?$',
        crud.ConferenceCRUDView.as_view(),
        name='conference_crud_view'),

    url(r'^crud/studentconference/?$',
        crud.StudentConferenceCRUDView.as_view(),
        name='student_conference_crud_view'),

    url(r'^crud/test/?$',
        crud.TestCRUDView.as_view(),
        name='test_crud_view'),

    url(r'^crud/test_answer/?$',
        crud.TestAnswerCRUDView.as_view(),
        name='test_answer_crud_view'),

    url(r'^conference/upload_image/(?P<conference_id>[0-9]+)?$',
        crud.UploadConferenceImage.as_view(),
        name='up_conf_img'),

    url(r'^crud/conferenceimage/?$',
        crud.ConferenceImageCRUDView.as_view(),
        name='conferenceimage_crud_view'),

    url(r'^crud/studentconferenceimage/?$',
        crud.StudentConferenceImageCRUDView.as_view(),
        name='student_conferenceimage_crud_view'),

    url(r'^crud/question/?$',
        crud.QuestionCRUDView.as_view(),
        name='question_crud_view'),

    url(r'^crud/predval/?$',
        crud.PredictionValidationCRUDView.as_view(),
        name='prediction_validation_crud_view'),

    url(r'^crud/studentquestion/?$',
        crud.StudentQuestionCRUDView.as_view(),
        name='student_question_crud_view'),

    url(r'^crud/questionimage/?$',
        crud.QuestionImageCRUDView.as_view(),
        name='questionimage_crud_view'),

    url(r'^crud/studentquestionimage/?$',
        crud.StudentQuestionImageCRUDView.as_view(),
        name='student_questionimage_crud_view'),

    url(r'^crud/questionexplainationimage/?$',
        crud.QuestionImageExplainationCRUDView.as_view(),
        name='questionexplainationimage_crud_view'),

    url(r'^crud/studentquestionexplainationimage/?$',
        crud.StudentQuestionImageCRUDView.as_view(),
        name='student_questionexplainationimage_crud_view'),

    url(r'^crud/answer/?$',
        crud.AnswerCRUDView.as_view(),
        name='answer_crud_view'),

    url(r'^crud/studentanswer/?$',
        crud.StudentAnswerCRUDView.as_view(),
        name='student_answer_crud_view'),

    url(r'^crud/studentanswerimage/?$',
        crud.StudentAnswerImageCRUDView.as_view(),
        name='student_answerimage_crud_view'),

    url(r'^crud/answerimage/?$',
        crud.AnswerImageCRUDView.as_view(),
        name='answerimage_crud_view'),

    url(r'^answer/upload_image/(?P<answer_id>[0-9]+)?$',
        crud.UploadAnswerImage.as_view(),
        name='up_answer_img'),

    url(r'^question/upload_image/(?P<question_id>[0-9]+)?$',
        crud.UploadQuestionImage.as_view(),
        name='up_question_img'),

    url(r'^question/upload_explainationimage/(?P<question_id>[0-9]+)?$',
        crud.UploadQuestionExplainationImage.as_view(),
        name='up_question_expimg'),
]

blousebrothers/users/urls.py
#detail -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from . import views


urlpatterns = [
    # URL pattern for the UserRedirectView
    url(
        regex=r'^compte/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^compte/(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^profile/update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
    # Wallet
    #url(r'^wallet/$', TemplateView.as_view(template_name='pages/wallet_teaser.html'), name='wallet'),
    url(
        regex=r'^wallet/$',
        view=views.UserWalletView.as_view(),
        name='wallet'
    ),
    # IBAN
    url(
        regex=r'^wallet/addbankaccount/$',
        view=views.AddIbanView.as_view(),
        name='addiban'
    ),
    # PAYOUT
    url(
        regex=r'^wallet/transfert/$',
        view=views.PayOutView.as_view(),
        name='payout'
    ),
    # Credit Card
    url(
        regex=r'^wallet/addcard/$',
        view=views.AddCardView.as_view(),
        name='addcard'
    ),
    # MangoPay Credit Card feed back
    url(
        regex=r'^wallet/addcardreturn/$',
        view=views.HandleMangoAddCardReturn.as_view(),
        name='addcardreturn'
    ),
    # Subscription
    url(
        regex=r'^abonnement/(?P<sub_id>[\d]*)$',
        view=views.Subscription.as_view(),
        name='subscription'
    ),
    # Inviations
    url(
        regex=r'^invitation/$',
        view=views.UserSendInvidation.as_view(),
        name='invitation'
    ),
    # SpecialOffer demand
    #url(
    #    regex=r'^specialoffer/$',
    #    view=views.SpecialOffer.as_view(),
    #    name='specialoffer'
    #),
    # ActivateOffer demand
    #url(
    #    regex=r'^activate/(?P<user_id>[\d]*)$',
    #    view=views.ActivateOffer.as_view(),
    #    name='activateoffer'
    #),
    # FAQ
    url(
        regex=r'^~FAQ$',
        view=views.FAQ.as_view(),
        name='faq'
    ),
    url(
        r'^$',
        RedirectView.as_view(url=reverse_lazy('users:subscription', args=['0'])),
        name='home'
    ),
  ]

config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView
from django.views import defaults as default_views
from django.contrib.sitemaps.views import sitemap

from paypal.express.dashboard.app import application as paypal

import blousebrothers.users.views
import blousebrothers.cards.views
import blousebrothers.dashboard.orders.views
import blousebrothers.checkout.views
from blousebrothers.app import application

from .sitemaps import StaticViewSitemap

sitemaps = {
    'static': StaticViewSitemap,
}

urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    url(r'^hijack/', include('hijack.urls')),
    url(r'^robots\.txt', include('robots.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^rules/$', TemplateView.as_view(template_name='pages/regledujeu.html'), name='regledujeu'),
    url(r'^invitations/', include('invitations.urls', namespace='invitations')),
    url(
        regex=r'^FAQ/',
        view=blousebrothers.users.views.FAQ.as_view(),
        name='faq'
    ),


    # Terms and Conditions
    url(r'^terms/', include('termsandconditions.urls')),

    # Paypal
    url(r'^checkout/paypal/', include('paypal.express.urls')),
    url(r'^dashboard/paypal/express/', include(paypal.urls)),


    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^mon/', include('blousebrothers.users.urls', namespace='users')),
    url(r'^ecni/', include('blousebrothers.confs.urls', namespace='confs')),
    url(r'^accounts/', include('allauth.urls')),

    # URL change redirection
    url(r'^catalogue/', RedirectView.as_view(url='/ecni/catalogue/')),
    url(r'^search/', RedirectView.as_view(url='/ecni/catalogue/')),

    # Your stuff: custom urls includes go here
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^signup/$', view=blousebrothers.users.views.SignupView.as_view(), name='signup'),
    url(r'^demologin$', view=blousebrothers.users.views.DemoLoginView.as_view(), name='demologin'),
    url(r'^demologout$', view=blousebrothers.users.views.DemoLogoutView.as_view(), name='demologout'),
    url(r'', include(application.urls)),
    url(r'^nested_admin/', include('nested_admin.urls')),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^revisions/', include('blousebrothers.cards.urls', namespace='cards')),
    url(r'^communaute/', include('blousebrothers.friends.urls', namespace='friends')),
    url(r'^facture/(?P<pk>\d+)/$', view=blousebrothers.dashboard.orders.views.PDFView.as_view(), name="invoice"),
    url(r'^facture_pdf/(?P<pk>\d+)/$', view=blousebrothers.dashboard.orders.views.PDFViewPrintView.as_view(),
        name="invoice_pdf"),
    url(r'^payments/', include('djstripe.urls', namespace="djstripe")),
    url(r'subscribe/', view=blousebrothers.cards.views.SubscribeView.as_view(), name='subscribe'),
    url(r'cancel_subscription/', view=blousebrothers.cards.views.CancelSubscription.as_view(),
        name='cancel_subscription'
        ),
    url(r'update_card/', view=blousebrothers.cards.views.UpdateCBView.as_view(), name='update_card'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

blousebrothers/basket/models.py
from oscar.apps.basket.models import *  # noqa

blousebrothers/checkout/models.py
from oscar.apps.checkout.models import *  # noqa

blousebrothers/dashboard/models.py
from oscar.apps.dashboard.models import *  # noqa

blousebrothers/partner/models.py
from oscar.apps.partner.models import *  # noqa

blousebrothers/catalogue/reviews/forms.py
from django.utils.translation import ugettext_lazy as _
from oscar.apps.catalogue.reviews.forms import ProductReviewForm as CoreProductReviewForm
from oscar.core.loading import get_model

ProductReview = get_model('reviews', 'productreview')


class ProductReviewForm(CoreProductReviewForm):
    class Meta:
        model = ProductReview
        fields = ('title', 'interest_score', 'clarity_score', 'correction_score',
                  'difficulty_score', 'body', 'name', 'email')
        labels = {
            'body': _('Commentaires libres'),
            'title': _('Titre'),
        }
        help_texts = {
            'body': _('Pas de spoiler ! Merci :-)'),
            'title': _("Soit juste dans ton évaluation, c'est important :-) !"),
        }

    def scores(self):
        fields = list(self)
        return fields[1:4]

blousebrothers/checkout/forms.py
from django import forms


class StripeTokenForm(forms.Form):
    stripeEmail = forms.EmailField(widget=forms.HiddenInput())
    stripeToken = forms.CharField(widget=forms.HiddenInput())

blousebrothers/dashboard/catalogue/forms.py
from django import forms
from oscar.apps.dashboard.catalogue.forms import ProductClassSelectForm as OriginalProductClassSelectForm
from oscar.apps.dashboard.catalogue.forms import ProductClass
from django.utils.translation import ugettext_lazy as _


class ProductClassSelectForm(OriginalProductClassSelectForm):
    product_class = forms.ModelChoiceField(
        label=_("Créer un nouveau sujet de type"),
        empty_label=_("-- Choose type --"),
        queryset=ProductClass.objects.all())

blousebrothers/templates/confs/base.html
{% extends "layout.html" %}
{% load activeurl %}

{% block subnavigation %}
{% include "confs/partials/tabs.html" %}
{% endblock subnavigation %}

blousebrothers/templates/confs/conference_delete.html
{% extends "layout.html" %}

{% block title %}Suppression de {{ object.title}}{% endblock %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    <p>Attention, Supprimer définitivement "{{ object }}" ?</p>
    <p>Si tu souhaites simplement dépublier ton dossier, <a href="{% url 'confs:final' object.slug %}">clique ici</a> et décoche la case "Publier". Tu pourras ainsi changer d'avis plus tard! :-)  ?</p>
	<input type="submit" value="Oui" />
        <a class="btn btn-primary" href="{% url 'confs:detail' object.slug %}">Non</a>
</form>
{% endblock content %}

blousebrothers/templates/confs/conference_detail.html
{% extends "layout.html" %}
{% load static %}
{% load i18n %}
{% load youtube %}
{% load bbtricks %}
{% load cropping %}

{% block title %}{{ object.title}}{% endblock %}

{% block submenu %}
      <a class="btn" href="{% url 'confs:edit' object.slug %}"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Editer la conférence</a>
     Rédaction complétée à {{ object.edition_progress }}%
      <a class="btn btn-danger pull-right" href="{% url 'confs:delete' object.slug %}"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Supprimer la conférence</a>
{% endblock %}
{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.title}}</h2>
    </div>
  </div>

<!-- Action buttons -->
  <div class="row">
  
    <div class="col-sm-12 ">
	  <legend>Détails </legend>
  	  <strong>Type :</strong> {{object.type}}<br>
  	  <strong>Items :</strong> {{object.items.all | join:", "}}<br>
  	  <strong>Specialités :</strong> {{object.specialities.all | join:", "}}<br>
  	  <strong>Esprit du dossier :</strong> {{object.summary|default:"<i>aucun</i>"}}<br>
	  <br>
	  {% if object.type == 'DCP' %}
	  <legend>Énoncé</legend><p> {{ object.statement | default:"<i>aucun</i>"}}<p>
	  <legend>Illustrations</legend>
	  {% for image in object.images.all %}
	  <div class="illustrations" id="images_div">
		  <figure>
		  <img src="{% cropped_thumbnail image "cropping" %}">
		  <figcaption>{{ image.caption }}</figcaption>
		  </figure>
	  </div>
	  {% empty %}
	  <i>Aucune</i>
	  {% endfor %}
	  {% endif %}
      <!-- Your Stuff: Custom user template urls -->
    </div>
    <h2>Questions</h2>
   
    {% for question in object.questions.all|dictsort:"index" %}
    <div class="well well-white">
	    <legend>Question {{ question.index | add:"1" }} {% if not question.is_valid %}<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>{% endif %}</legend>
      <div class="col-sm-12">
	      <strong>Énoncé :</strong><p>{{ question.question | default:"<i>aucun</i>" | safe }}</p>
      </div>
        {% if user.is_superuser %}
        {% with question.index as mindex %}
        <div><strong>Specialités proposées :</strong>{% for spe in specialities|index:mindex %} {{ spe }} ; {% endfor %}</div>
        {% endwith %}
        {% endif %}
      {% for image in question.images.all %}
      <div class="illustrations" id="images_div">
	      <figure>
	      <img src="{% cropped_thumbnail image "cropping" %}">
	      <figcaption>{{ image.caption }}</figcaption>
	      </figure>
      </div>
      {% endfor %}
      <strong>Correction globale :</strong><p>{{ question.explaination| default:"<i>aucune</i>" |safe }}</p>
      {% for image in question.explaination_images.all %}
      <div class="illustrations" id="images_div">
	      <figure>
	      <img src="{% cropped_thumbnail image "cropping" %}">
	      <figcaption>{{ image.caption }}</figcaption>
	      </figure>
      </div>
      {% endfor %}
      {% for answer in question.answers.all %}
      <div class="col-sm-12 {% if answer.correct %}correct{% else %}notcorrect{% endif %}">
	      <strong>Réponse {{ answer.index | to_char }} <i class="fa fa-{% if answer.correct %}check"{% else %}times"{% endif %} aria-hidden="true"></i>:</strong> <p>{{ answer.answer | default:"<i>A compléter</i>" }}</p>
	      <strong>Explication :</strong> <p>{{ answer.explaination | default:"<i>aucune</i>" | youtube | safe }}</p>
	      {% for image in answer.images.all %}
	      <div class="illustrations" id="images_div">
	        <figure>
	          <img src="{% cropped_thumbnail image "cropping" %}">
	      	  <figcaption>{{ image.caption }}</figcaption>
	        </figure>
	      </div>
	      {% endfor %}
      </div>
     {% endfor %}
   </div>
   {% endfor %}
  </div>
<!-- End Action buttons -->
</div>
{% endblock content %}

blousebrothers/templates/confs/conference_list.html
{% extends "confs/base.html" %}
{% load static %}
{% load i18n %}
{% load bbtricks %}
{% load currency_filters %}
{% load disqus_tags %}
{% block title %}{% trans 'Confs' %}{% endblock %}

{% block extrastyles %}
{{ block.super }}
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/3.3.4/css/bootstrap3/bootstrap-switch.min.css" rel="stylesheet" />
{% endblock %}

{% block cdn_scripts %}
{{ block.super }}
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/3.3.4/js/bootstrap-switch.min.js"></script>
{% endblock %}

{% block onbodyload %}
var toggle_correction= function(event, state) {
$.ajax({
url: "{% url 'confs:switch_correction' %}?conf_id=" + this.dataset.confId + "&state=" + state,
});
}
$("[name='switch_correction']").bootstrapSwitch('onText', 'Oui');
$("[name='switch_correction']").bootstrapSwitch('offText', 'Non');
$('input[name="switch_correction"]').on('switchChange.bootstrapSwitch', toggle_correction)
var toggle_for_sale= function(event, state) {
$.ajax({
url: "{% url 'confs:switch_for_sale' %}?conf_id=" + this.dataset.confId + "&state=" + state,
});
}
$("[name='switch_for_sale']").bootstrapSwitch('onText', 'Oui');
$("[name='switch_for_sale']").bootstrapSwitch('offText', 'Non');
$('input[name="switch_for_sale"]').on('switchChange.bootstrapSwitch', toggle_for_sale)

{% endblock %}


{% block content %}
<div class="container">

    <div class="row theader">
        <div class="col-md-6">
            <h2>{% trans 'Confs créées' %}</h2>
            <p>{% trans 'Éditer mes conférences' %}</p>
        </div>
        <div class="col-md-6">
            {% include 'partials/submenu_search.html' with actionurl="confs:list" %}
        </div>
    </div>

    <div class="list-group">
        {% for conference in conference_list %}
        <div class="list-group-item">
            <a href="#share_{{conference.slug}}" data-toggle="collapse" class="share"><i class="fa fa-share-alt-square" aria-hidden="true"></i></a>
            <div id="share_{{conference.slug}}" class="collapse share-group">
                {% include 'catalogue/partials/share_product.html' with product=conference.products.first %}
            </div>
            <div class="conf-title">
                <a href="{% url 'confs:detail' conference.slug %}" >
                    <h4 class="list-group-item-heading"><strong>{{ conference.title }}</strong><br>
                        <div class="hidden-xs"><i>- {{ conference.summary }} -</i></div>
                    </h4>
                </a>
            </div>


            <div class="panel-body">
                <ul class="col-md-12 stats">
                    <li class="stat col-md-3 col-sm-3 col-xs-6">
                        <span><b class="value">Conférence accessible</b><br></span>
                        <input type="checkbox" name="switch_for_sale"   data-size="mini" data-conf-id="{{conference.id}}"{% if conference.for_sale %} checked{% endif %}><br>
                    </li>
                    <li class="stat col-md-3 col-sm-3 col-xs-6">
                        <span><b class="value">Correction accessible</b><br></span>
                        <input type="checkbox" name="switch_correction"   data-size="mini" data-conf-id="{{conference.id}}"{% if conference.correction_dispo %} checked{% endif %}><br>
                    </li>
                    <li class="stat col-md-3 col-sm-3 col-xs-6">
                        <span><b class="value"><a href="{{ conference.products.first.get_absolute_url }}#disqus_thread" data-disqus-identifier="{{ conference.slug }}">Pas de commentaire</a>
                                {% disqus_num_replies %}
                            </b></span>

                            <em>Sur le forum</em>
                    </li>
                    <li class="stat col-md-3 col-sm-3 col-xs-6">
                        <span><b class="value">{{ conference | month_revenu | default:0 | currency }}</b><br> Revenus</span>
                        <em>Ce mois</em>
                    </li>
                </ul>
            </div>
        </div>
        <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="{{conference.edition_progress}}" aria-valuemin="0" aria-valuemax="100" style="width:{{conference.edition_progress}}%">
                {{conference.edition_progress}}%
            </div>
        </div>

        {% endfor %}

    </div>
    {% include 'partials/pagination.html' %}
</div>

{% endblock content %}

blousebrothers/templates/confs/create_form.html
{% load crispy_forms_tags %}
{% load static %}{% load i18n %}

{% if object %}
<form class="form" name="{{ form.form_name }}" novalidate enctype="multipart/form-data" method="post" action="{% url 'confs:edit' object.slug %}">
{% else %}
<form class="form" name="{{ form.form_name }}" novalidate enctype="multipart/form-data" method="post" action="{% url 'confs:create' %}">
{% endif %}
    {% csrf_token %}
    <div class="tab-content">
        <div id="conference">
            {{ form | crispy }}
            <a class="btn btn-success" href="https://form.jotformeu.com/gdebel/prepa_ecni_collaborative"><i class="fa fa-lightbulb-o" aria-hidden="true" style="font-size: 18pt;"></i> Ma conf est déjà sur un fichier ! Je vais pas tout retaper...</a>
        </div>
    </div>
    <br>
    <div class="control-group">
        <div class="controls">
            <button type="submit" class="btn">{% trans "Enregistrer et continuer" %} <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span></button>
        </div>
    </div>
</form>