blousebrothers/cards/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from . import views


urlpatterns = [
    url(regex=r'^$',
        view=RedirectView.as_view(url=reverse_lazy('cards:home'), permanent=True),
        name='root'
        ),
    url(regex=r'^partenariatnico$',
        view=views.BouletListView.as_view(),
        name='boulet'
        ),
    url(
        r'^mes/fiches$',
        view=views.ListCardView.as_view(),
        name='list'
    ),
    url(
        r'^fiches/oubliees$',
        view=views.ListTrashedCardView.as_view(),
        name='trashed'
    ),
    url(
        r'^fiches/nonvues$',
        view=views.UnseenCardsListView.as_view(),
        name='unseen_cards_list'
    ),
    url(
        regex=r'^fiches/(?P<pk>\d+)/fin/$',
        view=views.FinalizeCardView.as_view(),
        name='finalize'
    ),
    url(
        regex=r'^fiche/create/$',
        view=views.CreateCardView.as_view(),
        name='create'
    ),
    url(
        regex=r'^fiche/(?P<pk>\d+)/edit$',
        view=views.UpdateCardView.as_view(),
        name='update'
    ),
    url(
        regex=r'^fiche/(?P<id>\w+)/stop$',
        view=views.RevisionCloseSessionView.as_view(),
        name='stop'
    ),
    url(
        regex=r'^oublie/(?P<pk>\d+)$',
        view=views.RevisionDeleteView.as_view(),
        name='delete'
    ),
    url(
        regex=r'^fiches$',
        view=views.RevisionRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^letsgo$',
        view=views.RevisionRedirectView.as_view(),
        name='start_new_session'
    ),
    url(
        regex=r'^fiche/suivante/([0-9]+)$',
        view=views.RevisionNextCardView.as_view(),
        name='next'
    ),
    url(
        regex=r'^fiche/precedente/([0-9]+)$',
        view=views.RevisionPreviousCardView.as_view(),
        name='previous'
    ),
    url(
        regex=r'^fiche/(?P<id>\d+)/(?P<dsp_card_on_load>\w*)?$',
        view=views.RevisionView.as_view(),
        name='revision'
    ),
    url(
        regex=r'^fiche/bookmark/([0-9]+)$',
        view=views.bookmark_card,
        name='bookmark'
    ),
    url(
        regex=r'^anki$',
        view=views.AnkiUploadView.as_view(),
        name='ankiupload'
    ),
    url(
        regex=r'^dashboard$',
        view=views.RevisionHome.as_view(),
        name='home'
    ),
    url(
        regex=r'^matieres$',
        view=views.RevisionGroups.as_view(),
        name='revision_groups'
    ),
]

blousebrothers/confs/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.views.generic.base import RedirectView

from . import views
from . import crud

from jchart.views import ChartView
from blousebrothers.users.charts import MeanBarChart
mb_chart = MeanBarChart()

urlpatterns = [
    url(regex=r'^$',
        view=RedirectView.as_view(url=reverse_lazy('catalogue:index'), permanent=True),
        name='root'
        ),
    url(
        r'^charts/mean_chart/(?P<user_id>\d+)/(?P<friend_id>\d+)?$',
        ChartView.from_chart(mb_chart),
        name='mb_chart'
    ),
    # URL pattern for the ConferenceHomeView
    url(
        r'^dashboard$',
        view=views.ConferenceHomeView.as_view(),
        name='home'
    ),
    # URL pattern for the ConferenceListView
    url(
        r'^mes_dossiers/?$',
        view=views.ConferenceListView.as_view(),
        name='list'
    ),

    # URL pattern for the TestUpdateView
    url(
        regex=r'^dossier/(?P<slug>[\w.@+-]+)$',
        view=views.TestUpdateView.as_view(),
        name='test'
    ),
    # URL pattern for the TestResetView
    url(
        regex=r'^dossier/(?P<slug>[\w.@+-]+)/resettest$',
        view=views.TestResetView.as_view(),
        name='test_reset'
    ),

    # URL pattern for the TestUpdateView
    url(
        regex=r'^dossier/(?P<slug>[\w.@+-]+)/resultats$',
        view=views.TestResult.as_view(),
        name='result'
    ),


    # URL pattern for the ConferenceDetailView
    url(
        regex=r'^dossier/(?P<slug>[\w.@+-]+)/$',
        view=views.ConferenceDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the ConferenceUpdateView
    url(
        regex=r'^creation/(?P<slug>[\w.@+-]+)/update$',
        view=views.ConferenceUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^~create/(?P<slug>[\w.@+-]+)/update$',
        view=RedirectView.as_view(pattern_name='confs:update', permanent=True),
        name='oldupdate'
    ),
    url(
        regex=r'^creation/(?P<slug>[\w.@+-]+)/delete$',
        view=views.ConferenceDeleteView.as_view(),
        name='delete'
    ),
    url(
        regex=r'^creation/(?P<slug>[\w.@+-]+)/final$',
        view=views.ConferenceFinalView.as_view(),
        name='final'
    ),
    # URL pattern for the ConferenceUpdateView
    url(
        regex=r'^creation/$',
        view=views.ConferenceCreateView.as_view(),
        name='create'
    ),
    url(
        regex=r'^creation/(?P<slug>[\w.@+-]+)/edit$',
        view=views.ConferenceEditView.as_view(),
        name='edit'
    ),
    url(r'^dossiers_faits/?$',
        views.BuyedConferenceListView.as_view(),
        name='my_confs'),

    url(r'^switch_correction$',
        view=views.ajax_switch_correction,
        name="switch_correction",
        ),
    url(r'^switch_for_sale$',
        view=views.ajax_switch_for_sale,
        name="switch_for_sale",
        ),


    #   #####  ############  #####   #
    #    ###   # CRUD API #   ###    #
    #     #    ############    #     #

    url(r'^crud/conference/?$',
        crud.ConferenceCRUDView.as_view(),
        name='conference_crud_view'),

    url(r'^crud/studentconference/?$',
        crud.StudentConferenceCRUDView.as_view(),
        name='student_conference_crud_view'),

    url(r'^crud/test/?$',
        crud.TestCRUDView.as_view(),
        name='test_crud_view'),

    url(r'^crud/test_answer/?$',
        crud.TestAnswerCRUDView.as_view(),
        name='test_answer_crud_view'),

    url(r'^conference/upload_image/(?P<conference_id>[0-9]+)?$',
        crud.UploadConferenceImage.as_view(),
        name='up_conf_img'),

    url(r'^crud/conferenceimage/?$',
        crud.ConferenceImageCRUDView.as_view(),
        name='conferenceimage_crud_view'),

    url(r'^crud/studentconferenceimage/?$',
        crud.StudentConferenceImageCRUDView.as_view(),
        name='student_conferenceimage_crud_view'),

    url(r'^crud/question/?$',
        crud.QuestionCRUDView.as_view(),
        name='question_crud_view'),

    url(r'^crud/predval/?$',
        crud.PredictionValidationCRUDView.as_view(),
        name='prediction_validation_crud_view'),

    url(r'^crud/studentquestion/?$',
        crud.StudentQuestionCRUDView.as_view(),
        name='student_question_crud_view'),

    url(r'^crud/questionimage/?$',
        crud.QuestionImageCRUDView.as_view(),
        name='questionimage_crud_view'),

    url(r'^crud/studentquestionimage/?$',
        crud.StudentQuestionImageCRUDView.as_view(),
        name='student_questionimage_crud_view'),

    url(r'^crud/questionexplainationimage/?$',
        crud.QuestionImageExplainationCRUDView.as_view(),
        name='questionexplainationimage_crud_view'),

    url(r'^crud/studentquestionexplainationimage/?$',
        crud.StudentQuestionImageCRUDView.as_view(),
        name='student_questionexplainationimage_crud_view'),

    url(r'^crud/answer/?$',
        crud.AnswerCRUDView.as_view(),
        name='answer_crud_view'),

    url(r'^crud/studentanswer/?$',
        crud.StudentAnswerCRUDView.as_view(),
        name='student_answer_crud_view'),

    url(r'^crud/studentanswerimage/?$',
        crud.StudentAnswerImageCRUDView.as_view(),
        name='student_answerimage_crud_view'),

    url(r'^crud/answerimage/?$',
        crud.AnswerImageCRUDView.as_view(),
        name='answerimage_crud_view'),

    url(r'^answer/upload_image/(?P<answer_id>[0-9]+)?$',
        crud.UploadAnswerImage.as_view(),
        name='up_answer_img'),

    url(r'^question/upload_image/(?P<question_id>[0-9]+)?$',
        crud.UploadQuestionImage.as_view(),
        name='up_question_img'),

    url(r'^question/upload_explainationimage/(?P<question_id>[0-9]+)?$',
        crud.UploadQuestionExplainationImage.as_view(),
        name='up_question_expimg'),
]

blousebrothers/friends/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from . import views


urlpatterns = [
    url(regex=r'^$',
        view=RedirectView.as_view(url=reverse_lazy('friends:group'), permanent=False),
        name='root'
        ),
    url(
        regex=r'^amis/liste$',
        view=views.FriendsListView.as_view(),
        name='friends_list'
    ),
    url(
        regex=r'^amis$',
        view=views.FriendsView.as_view(),
        name='home'
    ),
    url(
        regex=r'^groupes$',
        view=views.GroupView.as_view(),
        name='group'
    ),
    url(
        regex=r'^groupes/update/(?P<pk>\d+)$',
        view=views.GroupUpdateView.as_view(),
        name='group_detail'
    ),
    url(
        regex=r'^groupes/create$',
        view=views.GroupCreateView.as_view(),
        name='create_group'
    ),
    url(
        regex=r'^accept_member$',
        view=views.AcceptMemberView.as_view(),
        name='accept_member'
    ),
    url(
        regex=r'^refuse_member$',
        view=views.RefuseMemberView.as_view(),
        name='refuse_member'
    ),
    url(
        regex=r'^accept_group_invit$',
        view=views.AcceptGroupInvit.as_view(),
        name='accept_group_invit'
    ),
    url(
        regex=r'^refuse_group_invit$',
        view=views.RefuseGroupInvitView.as_view(),
        name='refuse_group_invit'
    ),
    url(
        regex=r'^remove_member$',
        view=views.RemoveMemberView.as_view(),
        name='remove_member'
    ),
    url(
        regex=r'^accept$',
        view=views.AcceptFriendsView.as_view(),
        name='accept_friend'
    ),
    url(
        regex=r'^refuse$',
        view=views.RefuseFriendsView.as_view(),
        name='refuse_friend'
    ),
    url(
        regex=r'^remove_friend$',
        view=views.RemoveFriendsView.as_view(),
        name='remove_friend'
    ),
    url(
        regex=r'^share_cards$',
        view=views.update_sharecards,
        name='share_cards'
    ),
    url(
        regex=r'^share_results$',
        view=views.update_shareresults,
        name='share_results'
    ),
    url(
        regex=r'^share_confs$',
        view=views.update_shareconfs,
        name='share_confs'
    ),
]

blousebrothers/users/urls.py
#detail -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from . import views


urlpatterns = [
    # URL pattern for the UserRedirectView
    url(
        regex=r'^compte/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^compte/(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^profile/update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
    # Wallet
    #url(r'^wallet/$', TemplateView.as_view(template_name='pages/wallet_teaser.html'), name='wallet'),
    url(
        regex=r'^wallet/$',
        view=views.UserWalletView.as_view(),
        name='wallet'
    ),
    # IBAN
    url(
        regex=r'^wallet/addbankaccount/$',
        view=views.AddIbanView.as_view(),
        name='addiban'
    ),
    # PAYOUT
    url(
        regex=r'^wallet/transfert/$',
        view=views.PayOutView.as_view(),
        name='payout'
    ),
    # Credit Card
    url(
        regex=r'^wallet/addcard/$',
        view=views.AddCardView.as_view(),
        name='addcard'
    ),
    # MangoPay Credit Card feed back
    url(
        regex=r'^wallet/addcardreturn/$',
        view=views.HandleMangoAddCardReturn.as_view(),
        name='addcardreturn'
    ),
    # Subscription
    url(
        regex=r'^abonnement/(?P<sub_id>[\d]*)$',
        view=views.Subscription.as_view(),
        name='subscription'
    ),
    # Inviations
    url(
        regex=r'^invitation/$',
        view=views.UserSendInvidation.as_view(),
        name='invitation'
    ),
    # SpecialOffer demand
    #url(
    #    regex=r'^specialoffer/$',
    #    view=views.SpecialOffer.as_view(),
    #    name='specialoffer'
    #),
    # ActivateOffer demand
    #url(
    #    regex=r'^activate/(?P<user_id>[\d]*)$',
    #    view=views.ActivateOffer.as_view(),
    #    name='activateoffer'
    #),
    # FAQ
    url(
        regex=r'^~FAQ$',
        view=views.FAQ.as_view(),
        name='faq'
    ),
    url(
        r'^$',
        RedirectView.as_view(url=reverse_lazy('users:subscription', args=['0'])),
        name='home'
    ),
  ]

config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView
from django.views import defaults as default_views
from django.contrib.sitemaps.views import sitemap

from paypal.express.dashboard.app import application as paypal

import blousebrothers.users.views
import blousebrothers.cards.views
import blousebrothers.dashboard.orders.views
import blousebrothers.checkout.views
from blousebrothers.app import application

from .sitemaps import StaticViewSitemap

sitemaps = {
    'static': StaticViewSitemap,
}

urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    url(r'^hijack/', include('hijack.urls')),
    url(r'^robots\.txt', include('robots.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^rules/$', TemplateView.as_view(template_name='pages/regledujeu.html'), name='regledujeu'),
    url(r'^invitations/', include('invitations.urls', namespace='invitations')),
    url(
        regex=r'^FAQ/',
        view=blousebrothers.users.views.FAQ.as_view(),
        name='faq'
    ),


    # Terms and Conditions
    url(r'^terms/', include('termsandconditions.urls')),

    # Paypal
    url(r'^checkout/paypal/', include('paypal.express.urls')),
    url(r'^dashboard/paypal/express/', include(paypal.urls)),


    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^mon/', include('blousebrothers.users.urls', namespace='users')),
    url(r'^ecni/', include('blousebrothers.confs.urls', namespace='confs')),
    url(r'^accounts/', include('allauth.urls')),

    # URL change redirection
    url(r'^catalogue/', RedirectView.as_view(url='/ecni/catalogue/')),
    url(r'^search/', RedirectView.as_view(url='/ecni/catalogue/')),

    # Your stuff: custom urls includes go here
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^signup/$', view=blousebrothers.users.views.SignupView.as_view(), name='signup'),
    url(r'^demologin$', view=blousebrothers.users.views.DemoLoginView.as_view(), name='demologin'),
    url(r'^demologout$', view=blousebrothers.users.views.DemoLogoutView.as_view(), name='demologout'),
    url(r'', include(application.urls)),
    url(r'^nested_admin/', include('nested_admin.urls')),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^revisions/', include('blousebrothers.cards.urls', namespace='cards')),
    url(r'^communaute/', include('blousebrothers.friends.urls', namespace='friends')),
    url(r'^facture/(?P<pk>\d+)/$', view=blousebrothers.dashboard.orders.views.PDFView.as_view(), name="invoice"),
    url(r'^facture_pdf/(?P<pk>\d+)/$', view=blousebrothers.dashboard.orders.views.PDFViewPrintView.as_view(),
        name="invoice_pdf"),
    url(r'^payments/', include('djstripe.urls', namespace="djstripe")),
    url(r'subscribe/', view=blousebrothers.cards.views.SubscribeView.as_view(), name='subscribe'),
    url(r'cancel_subscription/', view=blousebrothers.cards.views.CancelSubscription.as_view(),
        name='cancel_subscription'
        ),
    url(r'update_card/', view=blousebrothers.cards.views.UpdateCBView.as_view(), name='update_card'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

blousebrothers/basket/models.py
from oscar.apps.basket.models import *  # noqa

blousebrothers/checkout/models.py
from oscar.apps.checkout.models import *  # noqa

blousebrothers/dashboard/models.py
from oscar.apps.dashboard.models import *  # noqa

blousebrothers/checkout/forms.py
from django import forms


class StripeTokenForm(forms.Form):
    stripeEmail = forms.EmailField(widget=forms.HiddenInput())
    stripeToken = forms.CharField(widget=forms.HiddenInput())

blousebrothers/templates/friends/base.html
{% extends "layout.html" %}
{% load activeurl %}

{% block subnavigation %}
<div class="pagehead repohead instapaper_ignore experiment-repo-nav">
    <div class="container">
        {% activeurl css_class="selected" parent_tag="self" %}
        <nav class="reponav">
            <a href="{% url 'friends:group' %}" class="reponav-item">
                <i class="fa fa-users" aria-hidden="true"></i>
                <span itemprop="name">Groupes, Tutorats
                </span>
                {% if user.active_group_invits.count %}
                <span class="Counter">{{ user.active_group_invits.count }}
                </span>
                {% endif %}
            </a>    
            <a href="{% url 'friends:home' %}" class="reponav-item">
                <i class="fa fa-comments" aria-hidden="true"></i>
                <span>Amis
                </span>
                {% if user.nb_activ_friendship_offers  %}
                <span class="Counter">{{ user.nb_activ_friendship_offers }}
                </span>
                {% endif %}
            </a>  
        </nav>
        {% endactiveurl %}
    </div>
</div>
{% endblock subnavigation %}

blousebrothers/templates/friends/friends_list.html
{% extends "friends/base.html" %}
{% load i18n %}
{% load bbtricks %}

{% block title %}{% trans 'Mes amis' %}{% endblock %}


{% block content %}
<div class="container">
    <div class="row theader">
        <a href={% url 'friends:home' %}><i class="fa fa-chevron-left"></i> Retour</a>
        <div class="space12"></div>
        <div class="col-md-12">
            {% include 'partials/submenu_search.html' with actionurl="friends:friends_list" %}
            <div class="x_panel tile fixed_height_320">
                <div class="x_title">
                    <h2><i class="fa fa-arrows-h"></i> Partages{% if user.friends.count <= 1 %} <small>(tu es ami avec nous pour commencer :)</small>{% endif %}</h2>
                    <div class="clearfix">{{ user.friends.count }}
                    </div>
                </div>
                <div class="x_content">
                    <div class="dashboard-widget-content">
						<div class="space12"></div> <!-- 40px Vertical Spacing -->
                        <ul class="list-unstyled msg_list">
                            {% for relation in object_list %}
                            <li>
                                <div class="friends-profile hidden-xs"> 
                                    <span class="image">
                                        <img style="width: 100px;" src="{{relation.user.socialaccount_set.first.get_avatar_url | default_icon }}" alt="avatar">
                                    </span>
                                    <span class="share_cards">
                                        <br>
                                        {% with total=relation.user.created_cards.count %}
                                        {{ total }} carte{{ total|pluralize }} crée{{ total|pluralize }}.<br>
                                        {% endwith %}
                                        {% with total=relation.user.nb_tests_done %}
                                        {{ total }} dossier{{ total|pluralize }} fait{{ total|pluralize }}.<br>
                                        {% endwith %}
                                        {% with total=relation.user.nb_created_confs %}
                                        {{ total }} dossier{{ total|pluralize }} créé{{ total|pluralize }}.<br>
                                        {% endwith %}
                                    </span>
                                </div>
                                <div class="share_cards">
                                    <label class="hidden-xs">Partages</label><br>
                                    Cartes<br>
                                    Résultats<br>
                                    Dossiers<br>
                                </div>
                                <div class="share_cards text-center">
                                    <label>{{ relation.user.username }}</label><br>
                                    {{ relation.share_cards |yesno:"Oui,Non" }}<br>
                                    {{ relation.share_results |yesno:"Oui,Non" }}<br>
                                    {{ relation.share_confs |yesno:"Oui,Non" }}<br>
                                </div>
                                <div class="share_cards text-center">
                                    <label>Moi</label><br>
                                    <input type="checkbox" name="share_cards"   data-size="mini" data-friend-id="{{relation.user.id}}"{% if relation.i_share_cards %} checked{% endif %}><br>
                                    <input type="checkbox" name="share_results" data-size="mini" data-friend-id="{{relation.user.id}}"{% if relation.i_share_results %} checked{% endif %}><br>
                                    <input type="checkbox" name="share_confs" data-size="mini" data-friend-id="{{relation.user.id}}"{% if relation.i_share_confs %} checked{% endif %}><br>
                                </div>
                                <div class="friends-control"> 
                                    <label class="hidden-xs">Supprimer</label><br>
                                    <a href="{% url 'friends:remove_friend' %}?pk={{ relation.user.id}}" class="btn btn-danger"><i class="fa fa-times fa-lg"></i></a>
                                </div>
                            </li>
                            {% endfor %}
                        </ul>
						
					</div>
				</div>
            </div>
        </div>
        {% include 'partials/pagination.html' %}
    </div>
</div>
{% endblock content %}

{% block extrastyles %}
{{ block.super }}
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/3.3.4/css/bootstrap3/bootstrap-switch.min.css" rel="stylesheet" />
{% endblock %}

{% block onbodyload %}
var toggle_share_results = function(event, state) {
    $.ajax({
        url: "{% url 'friends:share_results' %}?friend_id=" + this.dataset.friendId + "&state=" + state,
    });
}
var toggle_share_confs = function(event, state) {
    $.ajax({
        url: "{% url 'friends:share_confs' %}?friend_id=" + this.dataset.friendId + "&state=" + state,
    });
}
$("[name='share_cards']").bootstrapSwitch('onText', 'Oui');
$("[name='share_cards']").bootstrapSwitch('offText', 'Non');
$("[name='share_results']").bootstrapSwitch('onText', 'Oui');
$("[name='share_results']").bootstrapSwitch('offText', 'Non');
$("[name='share_confs']").bootstrapSwitch('onText', 'Oui');
$("[name='share_confs']").bootstrapSwitch('offText', 'Non');
$('input[name="share_cards"]').on('switchChange.bootstrapSwitch', toggle_share_cards)
$('input[name="share_results"]').on('switchChange.bootstrapSwitch', toggle_share_results)
$('input[name="share_confs"]').on('switchChange.bootstrapSwitch', toggle_share_confs)

{% endblock %}

{% block cdn_scripts %}
{{ block.super }}
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/3.3.4/js/bootstrap-switch.min.js"></script>
{% endblock %}

blousebrothers/templates/friends/group_form.html
{% extends "friends/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <form action="" method="post">{% csrf_token %}
        {{ form | crispy }}
        <button class="btn btn-success" type="submit">Valider</button>
    </form>
</div>
{% endblock content %}